<a href="https://colab.research.google.com/github/Abhay7753/AI_ML_11sep/blob/main/Pandas_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [ ]:
# Student name
# Student Id
# branch
#  Attendance percentage
#  Examination marks
#  stduy hours
#  Placement status

In [ ]:
# Pandas can be used to perform the following :

Organizing data into rows and columns.
Reading data from CSV and Excel

In [1]:
student_names =["Aamit" ,"Priya" , "Rahul", "Sneha"]
marks = [85,92,67,78]

print(student_names)
print(marks)

['Aamit', 'Priya', 'Rahul', 'Sneha']
[85, 92, 67, 78]

In [2]:
import pandas as pd

In [4]:
pd.__version__

'2.2.3'

In [12]:
# Dictionary :
# Col1: names ---> [n1,n2 ..]
# col2 marks ---> [m1, m2...]

# pd.DataFrame(dict)


students ={ "Names": ["Amit" ,"Abhay","Aman","Ashish"],
             "Marks": [56,86,79,75]
             }
pd.DataFrame(students)

    Names  Marks
0    Amit     56
1   Abhay     86
2    Aman     79
3  Ashish     75

In [14]:
# Series
marks =pd.Series([85,92,67,78,90])
print(marks)

0    85
1    92
2    67
3    78
4    90
dtype: int64

In [15]:
temperatures =pd.Series([30,32,31,29,35,34,33])

In [17]:
temperatures.mean()

np.float64(32.0)

In [18]:
temperatures.max()

35

In [19]:
temperatures.min()

29

In [20]:
len(temperatures)

7

In [22]:
names = pd.Series(["AMit","Priya","Rahul","Sneha"])
print(names)

0     AMit
1    Priya
2    Rahul
3    Sneha
dtype: object

In [24]:
names = pd.Series(["AMit","Priya","Rahul","Sneha",25])
print(names)

0     AMit
1    Priya
2    Rahul
3    Sneha
4       25
dtype: object

In [25]:
# Month name ---> index
# sales ---> Series values


data =pd.Series([100,200,500,450])
data

0    100
1    200
2    500
3    450
dtype: int64

In [30]:

data =pd.Series( [100,200,500,450],
                index =["January" ,"Febuary" ,"March" ,"April"])
data

January    100
Febuary    200
March      500
April      450
dtype: int64

In [33]:
data[1]

/tmp/ipykernel_9755/3862107824.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[1]

np.int64(200)

In [34]:
data["Febuary"]

np.int64(200)

In [37]:
# What % of sales came from Jan ?
a =data["January"]*100/data.sum()
a

np.float64(8.0)

In [38]:
# Series
# Subjects ===> marks

data = pd.Series([100,80,90,45,70],
                 index = ["Python","SQL","ML","AI","Maths"])
data

Python    100
SQL        80
ML         90
AI         45
Maths      70
dtype: int64

In [41]:
s= {
    "Pythom":100,
    "SQL":85,
    "ML":90,
    "AI":45,
    "Maths":70


    }
s

{'Pythom': 100, 'SQL': 85, 'ML': 90, 'AI': 45, 'Maths': 70}

In [52]:
# Create a pandas series from numpy array

import numpy as np

num =np.array([45,69,5,8,48])

pd.Series(num)

0    45
1    69
2     5
3     8
4    48
dtype: int64

In [55]:
# Write a code to create a numpy array of marks (out of 100) and then assign 10 bonus marks to each.

arr = np.array([95 ,25 ,87 ,58, 48 ,89 ])
np.where( arr <=90 ,arr+10 ,arr)

array([95, 35, 97, 68, 58, 99])

In [56]:
new = np.minimum(marks+10,100)
new

0     95
1    100
2     77
3     88
4    100
dtype: int64

In [57]:
marks =pd.Series([60,70,80,90])
marks+5

0    65
1    75
2    85
3    95
dtype: int64